[tool.poetry]
name = "lockbox"
version = "0.1.0"
description = ""
authors = ["Kevin Yokley <kyokley2@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
mock = "^3.0"
pytest = "^5.0"
bandit = "^1.6"
bpython = "^0.18.0"
pdbpp = "^0.10.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
