#!/usr/bin/env python

from encrypt_file.main import encrypt, decrypt

def main():
    ciphertext = encrypt(b'asdf', b'this is a string')

    plaintext = decrypt(b'asdf', ciphertext)
    print(plaintext)

if __name__ == '__main__':
    main()
