#!/usr/bin/env python
"""lockbox

Usage:
    lockbox <cmd> [<input>] [options]
    lockbox --version

Arguments:
    cmd    encrypt or decrypt
    input  file to be used for input
           specify '-' to use stdin

Options:
    -o FILE --output=FILE   file to be used for outputted data
                            specifying an output file with a '.png'
                            extension will write a QR code to FILE

Without -o FILE given, lockbox will display data to stdout
"""
import getpass
import sys

from docopt import docopt
from blessings import Terminal

from lockbox import (encrypt,
                     decrypt,
                     encrypt_file,
                     decrypt_file,
                     LockBoxException,
                     )
from lockbox._version import get_versions


VERSION = get_versions()['version']
ENCRYPT = 'encrypt'
DECRYPT = 'decrypt'

term = Terminal()

def main(cmd, infile, outfile):
    if cmd not in (ENCRYPT, DECRYPT):
        print('{} is not a valid cmd. Must be either encrypt or decrypt'.format(cmd))
        print(__doc__)
        return

    stdin_data = None
    if not infile or infile == '-':
        stdin_data = sys.stdin.read().encode('utf-8')

    passphrase = getpass.getpass('Enter passphrase: ').encode('utf-8')

    if cmd == ENCRYPT:
        confirm_passphrase = getpass.getpass('Confirm passphrase: ').encode('utf-8')

        if passphrase != confirm_passphrase:
            print('passphrases do not match')
            return

        if stdin_data:
            stdout_data = encrypt(passphrase, stdin_data, outfile=outfile)
            if stdout_data:
                print(stdout_data.decode('utf-8'))
        else:
            encrypt_file(passphrase, infile, output_file=outfile)
    elif cmd == DECRYPT:
        if stdin_data:
            stdout_data = decrypt(passphrase, stdin_data, outfile=outfile)
            if stdout_data:
                print(stdout_data.decode('utf-8'))
        else:
            decrypt_file(passphrase, infile, output_file=outfile)


if __name__ == '__main__':
    args = docopt(__doc__, version=VERSION)

    if args['--version']:
        print(VERSION)
    else:
        cmd = args['<cmd>'].lower()
        infile = args['<input>']
        outfile = args['--output']

        try:
            main(cmd, infile, outfile)
        except LockBoxException as e:
            print(term.red(str(e)))
